....?

diff --git a/opt/bin/twotac b/opt/bin/twotac
--- a/opt/bin/twotac
+++ b/opt/bin/twotac
@@ -8,7 +8,7 @@ TWOTACCONFIGS="/opt/bin/twotacconfigs"
 TWOTACLOGS="/opt/bin/twotaclogs"
 CONFIGURED=false
 #This is where the current variables will be stored
-source $TACCONF || (echo "Configuration file missing! Check $TACCONF ASAP" >> $TACLOG && exit 1)
+source $TACCONF || {echo "Configuration file missing! Check $TACCONF ASAP" >> $TACLOG && exit 1}
 #trap '' 2
 ### Opening log announcement
 echo "<----`date`---->" >> $TACLOG
@@ -25,11 +25,11 @@ askfirstsetup () {
 		:
 	else
 		echo "...Running first time setup..." >> $TACLOG
-		source $TWOTACSETUP || (echo "Setup software missing!" >> $TACLOG && exit1)
+		source $TWOTACSETUP || echo "Setup software missing!" >> $TACLOG && exit1
 	fi
 } 
 stopfirstsetup () {
-	sed -i 's/FIRSTSETUP\=false/FIRSTSETUP\=true/g' $TACCONF || (echo "Configuration file missing! Check $TACCONF ASAP" >> $TACLOG && exit1)
+	sed -i 's/FIRSTSETUP\=false/FIRSTSETUP\=true/g' $TACCONF || {echo "Configuration file missing! Check $TACCONF ASAP" >> $TACLOG && exit1}
 	FIRSTSETUP=true
 	return 0
 }
@@ -88,13 +88,13 @@ do
 		[Ss] ) #This case sets $FIRSTSETUP to false, preventing prompts and popups
 			stopfirstsetup;;
 		1) #This case enters the user management interface
-			source $TWOTACUSERS || (echo "User management software missing! Check $TWOTACUSERS ASAP" >> $TACLOG && exit1);;
+			source $TWOTACUSERS || {echo "User management software missing! Check $TWOTACUSERS ASAP" >> $TACLOG && exit1};;
 		2) #This case will allow you to interact with the Logs and Backups menu
-			source $TWOTACLOGS || (echo "Log management software missing! Check $TWOTACLOGS ASAP" >> $TACLOG && exit1);;
+			source $TWOTACLOGS || {echo "Log management software missing! Check $TWOTACLOGS ASAP" >> $TACLOG && exit1};;
 		3) #This case sets up the hardcoded placeholder variables and makes them functional scripts in context
-			source $TWOTACSETUP || (echo "Setup software missing! Check $TWOTACSETUP ASAP" >> $TACLOG && exit1);;
+			source $TWOTACSETUP || {echo "Setup software missing! Check $TWOTACSETUP ASAP" >> $TACLOG && exit1};;
 		4) #This case enters the user management interface
-			source $TWOTACCONFIGS || (echo "Configuration management software missing! Check $TWOTACCONFIGS ASAP" >> $TACLOG && exit1);;
+			source $TWOTACCONFIGS || {echo "Configuration management software missing! Check $TWOTACCONFIGS ASAP" >> $TACLOG && exit1};;
 		[Qq] ) #This case will end the program
 			echo "<--------------END-LOG--------------->" >> $TACLOG
 			echo "" >> $TACLOG
